draw_set_color(c_white)
draw_set_font(font_dialog)
draw_set_halign(fa_left)
draw_set_valign(fa_bottom)
if(statu<3){
draw_text_scribble(0,room_height,Lang_GetString("str_gamejolt_hint"))}
draw_set_halign(fa_center)
draw_set_valign(fa_top)
if(statu=0){
draw_text_scribble(320,120,Lang_GetString("str_gamejolt_username"))}
if(statu=1){
draw_text_scribble(320,120,Lang_GetString("str_gamejolt_token"))}
if(statu=3){
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text_scribble(320,240,Lang_GetString("str_gamejolt_wait"))}
if(statu=4){
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
if(global.gj_error=0){
draw_text_scribble(320,240,Lang_GetString("str_gamejolt_success")+username+Lang_GetString("str_gamejolt_success1"))}
if(global.gj_error=1){
draw_text_scribble(320,240,Lang_GetString("str_gamejolt_failed"))}
}
draw_set_halign(fa_center)
draw_set_valign(fa_top)
draw_set_font(font_menu)
if(statu<3){
draw_text_transformed(315,220,keyboard_string,4,4,0)}
draw_set_halign(fa_left)
draw_set_valign(fa_top)
